### ISSUE TITLE
error when no log files

### ISSUE THREAD

**Issue by Yasser-A420** [stifskere/betterconsole#1]
If you dont add any sort of log file or object it'll throw an undefined error
```
yasseralshinawah@Yassers-MacBook-Pro dasu-v14 % node .
/Volumes/Storage/Development/dasu-v14/node_modules/@memw/betterconsole/index.cjs:49
    logR = options.logRoute;
                   ^

TypeError: Cannot read properties of undefined (reading 'logRoute')
    at module.exports (/Volumes/Storage/Development/dasu-v14/node_modules/@memw/betterconsole/index.cjs:49:20)
    at Object.<anonymous> (/Volumes/Storage/Development/dasu-v14/util/sharding.js:2:31)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
yasseralshinawah@Yassers-MacBook-Pro dasu-v14 % 
```

**Comment by stifskere** [comment]
Fixed
